kind: Service
apiVersion: v1
metadata:
  name: web-server
  namespace: default
  selfLink: /api/v1/namespaces/default/services/web-server
  uid: 5fb00522-b47f-11e9-addd-42010a80015e
  resourceVersion: '197507'
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32658
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
  selector:
    app: web-server
  clusterIP: 10.97.0.199
  type: LoadBalancer
  sessionAffinity: None
  externalTrafficPolicy: Cluster
status:
  loadBalancer: {}
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: web-server
  namespace: default
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/web-server
  uid: 5fc3b1c5-b47f-11e9-addd-42010a80015e
  resourceVersion: '197518'
  generation: 1
  labels:
    app: web-server
  annotations:
    deployment.kubernetes.io/revision: '1'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: web-server
    spec:
      containers:
        - name: web-server
          image: r.cfcr.io/macioa/macioa/homepage:master
          ports:
            - containerPort: 80
              protocol: TCP
            - containerPort: 443
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 40
      dnsPolicy: ClusterFirst
      securityContext: {}
      imagePullSecrets:
        - name: regcred
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 50%
  revisionHistoryLimit: 2147483647
  progressDeadlineSeconds: 2147483647
status:
  observedGeneration: 1
  replicas: 1
  updatedReplicas: 1
  unavailableReplicas: 1
  conditions:
    - type: Available
      status: 'False'
      reason: MinimumReplicasUnavailable
      message: Deployment does not have minimum availability.
